# Generated by Django 3.0.6 on 2020-05-31 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.FloatField(blank=True, default=None, null=True)),
                ('data_venc', models.DateField(null=True)),
                ('data_pgto', models.DateField(null=True)),
                ('situacao', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.FloatField(blank=True, default=None, null=True)),
                ('data', models.DateField(null=True)),
                ('data_rec', models.DateField(null=True)),
                ('situacao', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Forma_Receber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finan.Receber')),
            ],
        ),
        migrations.CreateModel(
            name='Forma_Pagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finan.Pagar')),
            ],
        ),
        migrations.CreateModel(
            name='Classifica_Receber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finan.Receber')),
            ],
        ),
        migrations.CreateModel(
            name='Classifica_Pagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finan.Pagar')),
            ],
        ),
    ]
