# Generated by Django 3.0.6 on 2020-06-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0002_auto_20200531_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagar',
            name='classifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finan.Classifica_Pagar'),
        ),
        migrations.AddField(
            model_name='pagar',
            name='forma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finan.Forma_Pagar'),
        ),
    ]
