# Generated by Django 3.0.6 on 2020-06-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0003_auto_20200603_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagar',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
