# Generated by Django 3.0.6 on 2020-06-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0004_auto_20200603_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagar',
            name='data_pgto',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pagar',
            name='data_venc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='receber',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
