# Generated by Django 3.0.6 on 2020-06-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0005_auto_20200603_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifica_receber',
            name='receber',
        ),
        migrations.RemoveField(
            model_name='forma_receber',
            name='receber',
        ),
        migrations.RemoveField(
            model_name='receber',
            name='data',
        ),
        migrations.AddField(
            model_name='receber',
            name='classifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finan.Classifica_Receber'),
        ),
        migrations.AddField(
            model_name='receber',
            name='data_venc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='receber',
            name='forma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finan.Forma_Receber'),
        ),
        migrations.AlterField(
            model_name='receber',
            name='data_rec',
            field=models.DateTimeField(null=True),
        ),
    ]
